version: '3.3'

services:

  database:
    container_name: database
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  django:
    build: .
    container_name: django
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./application:/root
    links:
      - database
    restart: unless-stopped

  webserver:
      image: nginx
      links:
        - django
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./application:/root
      restart: unless-stopped
