version: '3.3'

services:

  webserver:
    environment:
      - VIRTUAL_HOST=project.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=project.com
      - LETSENCRYPT_EMAIL=example@email.com

  django:
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
      - SITE_URL=project.com
      - CORS_ORIGIN_WHITELIST=project.com
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - SECRET_KEY
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_TLS

networks:
  default:
    external:
      name: webproxy
