version: '3.3'

services:

  webserver:
    environment:
      - VIRTUAL_HOST=project.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=project.com
      - LETSENCRYPT_EMAIL=example@email.com

  django:
    environment:
      - DATABASE_HOST
      - SITE_URL
      - DEBUG
      - EMAIL_HOST
      - EMAIL_PORT
      - SECRET_KEY

networks:
  default:
    external:
      name: webproxy
